task: Move to Spring boot 3
Unleash/unleash-spring-boot-starter pull request #17
Opened 2022-12-19 11:01 UTC by chriswk

### What
Spring Boot 2.7 introduced a new way of registering auto-configurators: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration
Spring Boot 3.0 deprecated the old way of registering auto-configuration with spring.factories.

This PR updates to use the new one, as well as including an embedded example folder and moving to java 17, since Spring Boot 3.0 requires Java 17

Related to #16

2023-01-18 03:04 UTC, praveenpg requested changes

2023-01-18 03:04 UTC, praveenpg commented on example/pom.xml
> +        <version>3.0.0</version>
Let's update this to 3.0.1 as that is the latest version of spring boot now

2023-01-20 14:01 UTC, chriswk commented on example/pom.xml
> +        <version>3.0.0</version>
agreed

2023-01-25 02:38 UTC, praveenpg approved these changes

2023-01-25 02:38 UTC, merged